[tool.poetry]
name = "mcp_shared_lib"
version = "0.1.0"
description = "Shared library for MCP (Model Context Protocol) components"
authors = [{ name = "MCP Team", email = "team@example.com" }]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.8"
pydantic = ">=2.0.0"
PyYAML = ">=6.0"
requests = ">=2.25.0"
typing-extensions = ">=4.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
black = ">=23.0.0"
isort = ">=5.10.0"
mypy = ">=1.0.0"
flake8 = ">=6.0.0"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
